/vis/open OGL
/control/saveHistory
#/vis/verbose errors
#/vis/viewer/set/background white
#/vis/geometry/set/colour all -1 0 0 0
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
#/vis/scene/add/axes
/vis/scene/add/date
/vis/scene/add/hits
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/gps/particle gamma
/gps/position 0.0 0.0 0.0 millimeter
/gps/direction 0 0 1
/gps/ene/mono 0.6617 MeV

